config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
	root 'movies#index'
	resources :questions, only: [:index, :show, :create] do
  resources :solutions, only: [:index, :create]
  end
	resources :aws_texts, only: [:index, :show]
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/aws_text.rb
class AwsText < ApplicationRecord
	validates :title, :content, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
	validates :title, :url, presence: true
end

app/models/question.rb
class Question < ApplicationRecord
	validates :title, :detail, presence: true

  has_many :solutions
end

app/models/solution.rb
class Solution < ApplicationRecord
  validates :answer, presence: true

  belongs_to :question
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
end

app/controllers/aws_texts_controller.rb
class AwsTextsController < ApplicationController

  def index
    @aws_texts = AwsText.all
  end

  def show
    @aws_text = AwsText.find(params[:id])
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

	def index
		@movies = Movie.all.order(created_at: :asc).page(params[:page]).per(10)
	end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

	def index
		@questions = Question.all
    @question = Question.new
  end

  def create
    @question = Question.create(question_params)
    if @question.save
      redirect_to questions_path, notice: "質問を投稿しました"
    else
      @questions = Question.all
      flash.now[:alert] = "入力に不備があります"
      render :index
    end
  end

  def show
    @question = Question.find(params[:id])
    @solution = Solution.new
    @solutions = @question.solutions
  end

  private
  def question_params
    params.require(:question).permit(:title, :detail)
  end
end

app/controllers/solutions_controller.rb
class SolutionsController < ApplicationController
  
  def create
    @question = Question.find(params[:question_id])
    @question.save!
    @solution = @question.solutions.create(solution_params)
    if @solution.save
      redirect_to "/questions/#{@question.id}", notice: "回答を投稿しました"
    else
      @solutions = @question.solutions
      flash.now[:alert] = "入力に不備があります"
      render "questions/show"
    end
  end

  private

  def solution_params
    params.require(:solution).permit(:answer)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def bootstrap_class_for(key)
    case key
    when "alert"
      "danger"
    when "notice"
      "info"
    end
  end
end

app/helpers/markdown_helper.rb
module MarkdownHelper
  def markdown(text)
    options = {
      hard_wrap:       true,
      space_after_headers: true,
    }

    extensions = {
      autolink:           true,
      no_intra_emphasis:  true,
      fenced_code_blocks: true,
    }

    unless @markdown
      renderer = Redcarpet::Render::HTML.new(options)
      @markdown = Redcarpet::Markdown.new(renderer, extensions)
    end

    @markdown.render(text).html_safe
  end
end

app/views/aws_texts/index.html.erb
<div id="container">
  <div class="text-center mt-5 mb-4">
    <h2>AWS講座</h2>
  </div>
  <p>注意！！！：AWSのEC2やRDSは有料サービスとなります。無駄な料金を請求されないためにも、不要なインスタンスは停止・削除をしてください。</p>

  <table class="table table-striped">
    <thead class="aws-table-head text-white bg-primary">
      <tr>
        <th class="w-1">No.</th>
        <th class="w-5">内容</th>
      </tr>
    </thead>
    <tbody>
      <% @aws_texts.each.with_index(1) do |aws_text, i|%>
      <tr>
        <td>
          <%= i %>
        </td>
        <td>
          <%= link_to aws_text.title, aws_text_path(aws_text) %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/aws_texts/show.html.erb
<h1><%= @aws_text.title %></h1>
<%= markdown(@aws_text.content) %>

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
  	<div class="alert alert-<%= bootstrap_class_for(key) %>">
  		<button type="button" class="close" data-dismiss="alert">x
  		</button>
    	<%= value %>
  	</div>
<% end %>

app/views/layouts/_navbar_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand ml-5 h5" href="#">Gyakuten</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=3#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="navbar-collapse collapse show" id="navbarNav" style="">
    <ul class="navbar-nav">
      <li class="nav-item active dropdown">
        <a class="nav-link dropdown-toggle ml-4 h6" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Rails
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="nav-item nav-link active text-primary" href="/">動画教材</a>
          <a class="nav-item nav-link active text-primary" href="#">テキスト教材</a>
          <a class="nav-item nav-link active text-primary" href="#">ライブコーディング</a>
          <a class="nav-item nav-link active text-primary" href="/questions">質問集</a>
        </div>
        </li>
        <li class="nav-item">
          <a class="nav-item nav-link active ml-4 h6" href="/aws_texts">AWS講座</a>
        </li>
        <li class="nav-item">
          <a class="nav-item nav-link active ml-4 h6" href="#">PHP講座</a>
        </li>
        <li class="nav-item">
          <a class="nav-item nav-link active ml-4 h6" href="#">対談</a>
        </li>
        <li class="nav-item">
          <a class="nav-item nav-link active ml-4 h6" href="#">情報発信</a>
        </li>
        <li class="nav-item">
          <a class="nav-item nav-link active ml-4 h6" href="#">動画編集講座</a>
        </li>
        <li class="nav-item">
          <a class="nav-item nav-link active ml-4 h6" href="#">ライティング講座</a>
        </li>
        <li class="nav-item">
          <a class="nav-item nav-link active ml-4 h6" href="#">LINE@</a>
        </li>
      <% if user_signed_in? %>
      <li class="nav-item">
        <a class="nav-item nav-link active ml-4 h6" rel="nofollow" data-method="delete" href="/users/sign_out">ログアウト</a>
      </li>

      <% else %>
      <li class="nav-item">
        <a class="nav-item nav-link active ml-4 h6" href="/users/sign_up">新規登録</a>
      </li>
      <li class="nav-item">
        <a class="nav-item nav-link active ml-4 h6" href="/users/sign_in">ログイン</a>
      </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>GyakutenCloneGroup</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>    
      <%= render partial: "layouts/navbar_header" %>
    </header>
      <main>
        <%= render partial: "layouts/flash" %>
        <%= yield %>
      </main>
    <footer>
    </footer>
  </body>
</html>

app/views/movies/index.html.erb
<% @movies.each.with_index(@movies.offset_value+1) do |movie, i| %>
<div class="mt-5">
  <div class="text-center">
    <h5>Lv.<%=i%> : <%=movie.title%></h5>
    <iframe width="560" height="315" src="<%= movie.url %>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
  </div>
</div>
<%end%>
<div class="mt-5">
  <div class="pagination justify-content-center">
    <%= paginate @movies %>
  </div>
</div>

app/views/questions/index.html.erb
<%= stylesheet_link_tag "_questions", :media => "all" %>
<div class="post-question">
  <h2>新規投稿</h2>

  <%= form_with model: @question, local: true do |f| %>
  <p>【質問】</p>
  <%= f.text_area :title, class:"question initial-height " %>
  <p>【詳細】</p>
  <%= f.text_area :detail, class:"detail initial-height" %>
  <%= f.submit "送信", data: { confirm: "新規投稿しますか？"}, class:"btn btn-primary btn-block btn-lg"  %>
  <% end %>
</div>

<% @questions.each do |question| %>
<div class="question-form">
  <div class="card"> 
    <div class="title-containar">
      <h5><%= link_to question.title, question_path(question), class:"title"%>
      </h5>
    </div>
  </div>   
</div>
<% end %>

app/views/questions/show.html.erb
<%= stylesheet_link_tag "_questions", :media => "all" %>

<div class="title-show">
  <h5>【質問】</h5>
  <%= markdown(@question.title) %>
</div>
<hr>
<div class="detail-show">
  <h5>【詳細】</h5>
  <%= markdown(@question.detail) %>
</div>

<% @solutions.each.with_index(1) do |solution, i| %>
<div class="answer-show">
  <h5>【回答<%= i %>】</h5>
  <hr>
  <%= markdown(solution.answer) %>
</div>
<% end %>

<div class="answer-question">
  <div class="answer-title">
    <h2>回答投稿</h2>
  </div>

  <%= form_with(model:[@question,@solution], local: true) do |f| %>
  <p>【回答】</p>
  <%= f.text_area :answer, class:"answer initial-height " %>
  <%= f.submit "送信", data: { confirm: "回答投稿しますか？"}, class:"btn btn-primary btn-block btn-lg"  %>
  <% end %>
</div>